# Generated by Django 2.2.5 on 2019-09-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='lost',
            name='roll',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
